-- CareerLens database schema for Supabase
-- Run this in Supabase Dashboard -> SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  selected_career text default 'AI / ML Engineer',
  created_at timestamptz default now()
);

create table if not exists public.user_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  skill_name text not null,
  progress integer not null default 0 check (progress between 0 and 100),
  updated_at timestamptz default now(),
  unique(user_id, skill_name)
);

create table if not exists public.saved_careers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  career_name text not null,
  created_at timestamptz default now(),
  unique(user_id, career_name)
);

alter table public.profiles enable row level security;
alter table public.user_progress enable row level security;
alter table public.saved_careers enable row level security;

create policy "Users can view own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can insert own profile" on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);

create policy "Users can view own progress" on public.user_progress for select using (auth.uid() = user_id);
create policy "Users can insert own progress" on public.user_progress for insert with check (auth.uid() = user_id);
create policy "Users can update own progress" on public.user_progress for update using (auth.uid() = user_id);

create policy "Users can view own saved careers" on public.saved_careers for select using (auth.uid() = user_id);
create policy "Users can insert own saved careers" on public.saved_careers for insert with check (auth.uid() = user_id);
create policy "Users can delete own saved careers" on public.saved_careers for delete using (auth.uid() = user_id);

-- Automatically create a profile when a new auth user signs up.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, new.raw_user_meta_data ->> 'full_name');
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
